version: "3.8"

services:
  recommender-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./data:/app/data
    restart: unless-stopped
